prerequisites:
	@dpkg -L graphviz python-pygments > /dev/null
	@which bundle > /dev/null || (echo "You need ruby bundler installed. See: http://gembundler.com/"; exit 1);
	@bundle install > /dev/null
