package main

import (
	"context"
	"errors"
	"log"
	"os"
	"os/signal"
	"syscall"

	rmq "github.com/rabbitmq/rabbitmq-amqp-go-client/pkg/rabbitmqamqp"
)

const brokerURI = "amqp://guest:guest@localhost:5672/"

func main() {
	// Create a context that will be canceled on SIGINT (Ctrl+C) or SIGTERM.
	ctx, cancel := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer cancel()
	env := rmq.NewEnvironment(brokerURI, nil)
	conn, err := env.NewConnection(ctx)
	if err != nil {
		log.Panicf("Failed to connect to RabbitMQ: %v", err)
	}
	defer func() {
		_ = env.CloseConnections(context.Background())
	}()

	qInfo, err := conn.Management().DeclareQueue(ctx, &rmq.AutoGeneratedQueueSpecification{
		IsExclusive:  false,
		IsAutoDelete: false,
	})
	if err != nil {
		log.Panicf("Failed to declare a queue: %v", err)
	}

	consume(ctx, conn, qInfo.Name())
	publish(ctx, conn, qInfo.Name(), "hello")

	log.Printf(" [*] Waiting for messages. To exit press CTRL+C")
	<-ctx.Done()
	log.Printf("Shutting down gracefully...")
}

func consume(ctx context.Context, conn *rmq.AmqpConnection, qName string) {
	consumer, err := conn.NewConsumer(ctx, qName, nil)
	if err != nil {
		log.Panicf("Failed to create consumer: %v", err)
	}

	go func() {
		for {
			delivery, err := consumer.Receive(ctx)
			if err != nil {
				if errors.Is(err, context.Canceled) {
					return
				}
				log.Panicf("Failed to receive a message: %v", err)
			}
			msg := delivery.Message()
			var body string
			if len(msg.Data) > 0 {
				body = string(msg.Data[0])
			}
			log.Printf("Received a message: %s", body)
			_ = delivery.Accept(ctx)
		}
	}()
}

func publish(ctx context.Context, conn *rmq.AmqpConnection, qName, text string) {
	publisher, err := conn.NewPublisher(ctx, &rmq.QueueAddress{Queue: qName}, nil)
	if err != nil {
		log.Panicf("Failed to create publisher: %v", err)
	}
	defer func() { _ = publisher.Close(context.Background()) }()

	res, err := publisher.Publish(ctx, rmq.NewMessage([]byte(text)))
	if err != nil {
		if errors.Is(err, context.Canceled) {
			return
		}
		log.Panicf("Failed to publish a message: %v", err)
	}
	switch res.Outcome.(type) {
	case *rmq.StateAccepted:
		log.Printf("Confirmed")
	case *rmq.StateRejected:
		log.Fatalf("Message was rejected: %v", res.Outcome)
	case *rmq.StateReleased:
		log.Fatalf("Message was released: %v", res.Outcome)
	case *rmq.StateModified:
		log.Fatalf("Message was modified: %v", res.Outcome)
	default:
		log.Fatalf("Unexpected publish outcome: %v", res.Outcome)
	}
}
