package main

import (
	"context"
	"log"

	rmq "github.com/rabbitmq/rabbitmq-amqp-go-client/pkg/rabbitmqamqp"
)

const brokerURI = "amqp://guest:guest@localhost:5672/"

func main() {
	ctx := context.Background()
	env := rmq.NewEnvironment(brokerURI, nil)
	conn, err := env.NewConnection(ctx)
	if err != nil {
		log.Panicf("Failed to connect to RabbitMQ: %v", err)
	}
	defer func() {
		_ = env.CloseConnections(context.Background())
	}()

	qInfo, err := conn.Management().DeclareQueue(ctx, &rmq.AutoGeneratedQueueSpecification{
		IsExclusive:  false,
		IsAutoDelete: false,
	})
	if err != nil {
		log.Panicf("Failed to declare a queue: %v", err)
	}

	consume(conn, qInfo.Name())
	publish(conn, qInfo.Name(), "hello")

	log.Printf(" [*] Waiting for messages. To exit press CTRL+C")
	select {}
}

func consume(conn *rmq.AmqpConnection, qName string) {
	ctx := context.Background()
	consumer, err := conn.NewConsumer(ctx, qName, nil)
	if err != nil {
		log.Panicf("Failed to create consumer: %v", err)
	}

	go func() {
		for {
			delivery, err := consumer.Receive(ctx)
			if err != nil {
				log.Printf("consumer receive: %v", err)
				return
			}
			msg := delivery.Message()
			var body string
			if len(msg.Data) > 0 {
				body = string(msg.Data[0])
			}
			log.Printf("Received a message: %s", body)
			_ = delivery.Accept(ctx)
		}
	}()
}

func publish(conn *rmq.AmqpConnection, qName, text string) {
	ctx := context.Background()
	publisher, err := conn.NewPublisher(ctx, &rmq.QueueAddress{Queue: qName}, nil)
	if err != nil {
		log.Panicf("Failed to create publisher: %v", err)
	}
	defer func() { _ = publisher.Close(context.Background()) }()

	res, err := publisher.Publish(ctx, rmq.NewMessage([]byte(text)))
	if err != nil {
		log.Panicf("Failed to publish a message: %v", err)
	}
	switch res.Outcome.(type) {
	case *rmq.StateAccepted:
		log.Printf("Confirmed")
	default:
		log.Printf("Unexpected outcome: %v", res.Outcome)
	}
}
